import { Component, signal } from '@angular/core';
import { DataTableLightComponent, DtlDataSchema, DtlColumnSchema } from 'data-table-light';

@Component({
    selector: 'app-root',
    imports: [DataTableLightComponent],
    templateUrl: './app.html',
    styleUrl: './app.scss'
})
export class App {

    // sampleData = signal([
    //   { id: 1, name: 'John Doe', email: 'john@example.com', age: 30, active: true },
    //   { id: 2, name: 'Jane Smith', email: 'jane@example.com', age: 25, active: false },
    //   { id: 3, name: 'Bob Johnson', email: 'bob@example.com', age: 35, active: true }
    // ]);

    // tableSchema = signal<DtlDataSchema>({
    //   columns: [
    //     { name: 'ID', field: 'id', canOrder: true, width: 80 },
    //     { name: 'Name', field: 'name', canOrder: true, canFilter: true },
    //     { name: 'Email', field: 'email', canFilter: true },
    //     { name: 'Age', field: 'age', type: 'number', canOrder: true, width: 100 },
    //     { name: 'Active', field: 'active', type: 'check', width: 80 }
    //   ],
    //   maxRows: 10,
    //   tableStriped: true,
    //   selectRows: 'single'
    // });

    tableSchema = signal<DtlDataSchema>(
        { "tableClass": ["table", "table-bordered", "table-striped", "table-list-container-pssstyle"], "tableStyle": { "min-width": "200px", "background-color": "white" }, "theadStyle": { "background-color": "#e6e6e6", "display": "grid", "grid-template-columns": "minmax(80px,100px) minmax(70px,85px) minmax(50px,65px) minmax(150px,1fr) minmax(80px,150px) minmax(80px,150px) minmax(150px,1fr) 95px 95px 40px minmax(100px,120px) 277px" }, "resizable": true, "tableStriped": true, "maxRows": null, "maxRowsOptions": [10, 15, 20, 30, 50, 100, 200, 300, 500], "noRowStr": "Nessun dato", "pagerBoundary": true, "pagerDirection": true, "pagerRotate": true, "pagerRowsName": "Righe:", "pagerPageName": "Pagina:", "otherData": { "kind": null }, "virtualScroll": true, "contentClass": ["full-screen-grid"], "tbodycontainerStyle": { "height": "100%" }, "selectRows": "multi", "columns": [{ "name": "Codice", "field": "code", "type": "nowrap", "width": { "min": 80, "max": 100 }, "canOrder": true, "sortField": "code_ord", "sortFieldPath": "{year}/{@PadStart|{incremental}|6|0}", "nameRendered": "Codice" }, { "name": "Data", "field": "documentDate", "type": "date", "width": { "min": 70, "max": 85 }, "canOrder": true, "nameRendered": "Data" }, { "name": "Cod.Cli", "field": "codcli", "type": "nowrap", "fieldPath": "{stakeholders[customer,kind].stakeholder.code}", "width": { "min": 50, "max": 65 }, "canOrder": true, "sortField": "codcli_ord", "sortFieldPath": "{@Number|{stakeholders[customer,kind].stakeholder.code}}", "nameRendered": "Cod.Cli" }, { "name": "Cliente", "field": "customer", "type": "nowrap", "fieldPath": "{stakeholders[customer,kind].stakeholder.name}", "width": { "min": 150, "max": "1fr" }, "canOrder": true, "nameRendered": "Cliente" }, { "name": "Riferimento", "field": "reference", "type": "nowrap", "width": { "min": 80, "max": 150 }, "canOrder": true, "nameRendered": "Riferimento" }, { "name": "Indirizzo", "field": "addressRif", "type": "nowrap", "fieldPath": "{@IsNull|{address.city}|{address.city}{@IsNull|{address.province}| ({address.province})|}|}", "width": { "min": 80, "max": 150 }, "tooltip": "<div style=\"min-width:400px\">{#@toAddress|}</div>", "canOrder": true, "nameRendered": "Indirizzo" }, { "name": "Descrizione", "field": "description", "type": "nowrap", "width": { "min": 150, "max": "1fr" }, "canOrder": true, "nameRendered": "Descrizione" }, { "name": "Imponibile", "field": "rateable", "type": "currency", "width": "95px", "horizontalAlign": "right", "canOrder": true, "nameRendered": "Imponibile" }, { "name": "Totale", "field": "total", "type": "currency", "width": "95px", "horizontalAlign": "right", "canOrder": true, "nameRendered": "Totale" }, { "name": "C.", "field": "isClosed", "width": "40px", "template": "<div class=\"badge badge-dark\" style=\"background-color: {@If|{isClosed}|green|{@If|{movedInChildrenRows}|orange|darkorange}}\" title=\"{@If|{isClosed}|Chiuso|{@If|{movedInChildrenRows}|Parzialmente evaso|Aperto}}\"><i class=\"{@If|{isClosed}|ft-check-circle|{@If|{movedInChildrenRows}|ft-minus|ft-x}}\"></i></div>", "canOrder": true, "sortField": "isClosed_ord", "sortFieldPath": "{@If|{isClosed}|2|{@If|{movedInChildrenRows}|1|0}}", "nameRendered": "C." }, { "name": "Stato", "field": "status", "fieldPath": "{status.status.description}", "width": { "min": 100, "max": 120 }, "type": "button", "tooltip": "<div style=\"min-width:300px\">Stato: <span class=\"text-bold\">{status.status.description}</span><br/>Data: {@IsNull|{status.date}|{@Date|{status.date}|DD/MM/YYYY HH:mm}|Non disponibile}<br/>Autore: {@IsNull|{status.stakeholder}|{status.stakeholder.name}|Non disponibile}<br/>Commento: <span class=\"text-italic\">{@IsNull|{status.notes}|Non disponibile}</span><br/></div>", "buttonConfig": { "name": "statusBtn", "callback": "changeStatus", "class": ["btn", "btn-sm"], "color": "{status.status.color}" }, "canOrder": true, "nameRendered": "Stato" }], "buttons": [{ "name": "print", "callback": "printReport", "iconClass": ["fa", "ft-printer"], "class": ["btn-warning", "btn", "btn-sm"], "title": "Stampa" }, { "name": "delete", "callback": "delete", "iconClass": ["fa", "ft-trash-2"], "class": ["btn-danger", "btn", "btn-sm"], "title": "Elimina" }, { "name": "relateDocuments", "callback": "relateDocuments", "iconClass": ["fa", "ft-layers"], "class": ["btn-primary", "btn", "btn-sm"], "title": "Visualizza documenti collegati" }, { "name": "detailGroupRows", "callback": "detailGroupRows", "iconClass": ["fa", "ft-grid"], "class": ["btn-primary", "btn", "btn-sm"], "title": "Visualizza dettagli evasioni righe in documenti collegati" }, { "name": "openBottomSheet", "callback": "openBottomSheet", "iconClass": ["fa", "ft-chevrons-down"], "class": ["btn-secondary", "btn", "btn-sm"], "title": "Espandi dettagli" }], "exportButtons": [{ "name": "exportCsv", "Type": "Excel", "allowColumnsSelection": true, "iconClass": { "fa": true, "fa-file-excel-o": true }, "class": { "btn-default": true, "btn": true, "btn-sm": true }, "title": "Esporta excel (xlsx)" }], "externalButtons": [{ "name": "detailRows", "callback": "detailRows", "iconClass": ["fa", "ft-list"], "class": ["btn-primary", "btn", "btn-sm"], "title": "Visualizza righe del documento" }, { "name": "documentRecap", "callback": "documentRecap", "iconClass": ["fa", "ft-layers"], "class": ["btn-warning", "btn", "btn-sm"], "title": "Visualizza riepilogo documento " }, { "name": "statusHistory", "callback": "statusHistory", "iconClass": ["icon-notebook"], "text": "Stati", "class": ["btn-primary", "btn", "btn-sm"], "title": "Visualizza lo storico stati del documento" }], "exportSchema": { "filename": "ordini_cliente", "exportColumns": [{ "name": "Codice", "field": "code" }, { "name": "Data", "field": "documentDate", "type": "date" }, { "name": "Cod.Cli", "field": "codcli", "fieldPath": "{stakeholders[customer,kind].stakeholder.code}" }, { "name": "Cliente", "field": "customer", "fieldPath": "{stakeholders[customer,kind].stakeholder.name}" }, { "name": "Riferimento", "field": "reference" }, { "name": "Indirizzo", "field": "addressRif", "fieldPath": "{@IsNull|{address.city}|{address.city}{@IsNull|{address.province}| ({address.province})|}|}" }, { "name": "Descrizione", "field": "description" }, { "name": "Imponibile", "field": "rateable", "type": "currency" }, { "name": "Stato", "field": "status", "fieldPath": "{status.status.description}" }, { "name": "Ordinato", "field": "ordered_null" }, { "name": "Data arrivo", "field": "arrivalDate_null" }, { "name": "Consegnato / installato", "field": "installed_null" }, { "name": "Note", "field": "notes_null" }] }, "tbodyStyle": { "display": "grid", "grid-template-columns": "minmax(80px,100px) minmax(70px,85px) minmax(50px,65px) minmax(150px,1fr) minmax(80px,150px) minmax(80px,150px) minmax(150px,1fr) 95px 95px 40px minmax(100px,120px) 277px" }, "filters": {} });
    sampleData = signal([
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 10,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-30T08:55:15.928841",
            "documentDate": "2025-06-30T00:00:00",
            "lastModifyDate": "2025-06-30T08:55:15.9288417",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": false,
            "rateableRows": 285.35000000,
            "rateable": 285.35000000,
            "levy": 62.78000000,
            "amount": 348.13000000,
            "total": 348.13000000,
            "reference": "08/07/2025",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SRL",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SRL",
                        "code": "192",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Relax Area",
                "street": "Via Example 20",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "ITA",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-30T08:55:15.9312812"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "10/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 9,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-30T08:54:40.6863093",
            "documentDate": "2025-06-30T00:00:00",
            "lastModifyDate": "2025-06-30T08:54:40.6863097",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": false,
            "rateableRows": 287.15000000,
            "rateable": 287.15000000,
            "levy": 63.17000000,
            "amount": 350.32000000,
            "total": 350.32000000,
            "reference": "04/07/2025",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SRL",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SRL",
                        "code": "192",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Relax Area",
                "street": "Via Example 20",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "ITA",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-30T08:54:40.6893924"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "9/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 8,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-27T08:41:15.1520626",
            "documentDate": "2025-06-27T00:00:00",
            "lastModifyDate": "2025-06-27T08:41:15.1520633",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": false,
            "rateableRows": 246.94000000,
            "rateable": 246.94000000,
            "levy": 9.88000000,
            "amount": 256.82000000,
            "total": 256.82000000,
            "reference": "xxxxxxxxx",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SOC.COOP. A R.L.",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SOC.COOP. A R.L.",
                        "code": "14",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Canteen",
                "street": "Via Example 28",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-27T08:41:15.1567521"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "8/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 7,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-26T12:24:13.1634148",
            "documentDate": "2025-06-26T00:00:00",
            "lastModifyDate": "2025-06-26T12:25:35.7385425",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": true,
            "rateableRows": 1042.50000000,
            "rateable": 1042.50000000,
            "levy": 41.70000000,
            "amount": 1084.20000000,
            "total": 1084.20000000,
            "reference": "xxxxxxxxx",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SOC.COOP. A R.L.",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SOC.COOP. A R.L.",
                        "code": "14",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Kitchen",
                "street": "Via Example 18",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-26T12:24:13.1680979"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "7/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 6,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-26T12:23:01.6330575",
            "documentDate": "2025-06-26T00:00:00",
            "lastModifyDate": "2025-06-26T12:23:01.6330583",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": false,
            "rateableRows": 54.30000000,
            "rateable": 54.30000000,
            "levy": 2.17000000,
            "amount": 56.47000000,
            "total": 56.47000000,
            "reference": "Ref 30/06",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SRL",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SRL",
                        "code": "192",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Kitchen",
                "street": "Via Example 19",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "IT",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-26T12:23:01.6357468"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "6/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 5,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-26T12:21:20.5393887",
            "documentDate": "2025-06-26T00:00:00",
            "lastModifyDate": "2025-06-26T12:21:20.5393896",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": false,
            "rateableRows": 55.50000000,
            "rateable": 55.50000000,
            "levy": 2.22000000,
            "amount": 57.72000000,
            "total": 57.72000000,
            "reference": "Ref 30/06",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SRL",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SRL",
                        "code": "192",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Kitchen",
                "street": "Via Example 43/A",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "IT",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-26T12:21:20.5419954"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "5/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 4,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-26T12:10:42.8807029",
            "documentDate": "2025-06-26T00:00:00",
            "lastModifyDate": "2025-06-26T12:19:13.7160687",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": true,
            "rateableRows": 82.00000000,
            "rateable": 82.00000000,
            "levy": 16.24000000,
            "amount": 98.24000000,
            "total": 98.24000000,
            "reference": "Ref",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company S.R.L",
                        "secondName": "",
                        "alias": "",
                        "name": "Company S.R.L",
                        "code": "6",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Nursery",
                "street": "Via Example  N.33",
                "city": "City",
                "province": "PR",
                "zipCode": "",
                "country": "",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-26T12:10:42.8830986"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "4/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 3,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-26T12:02:17.1024896",
            "documentDate": "2025-06-26T00:00:00",
            "lastModifyDate": "2025-06-26T12:03:04.4517825",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": true,
            "rateableRows": 92.05000000,
            "rateable": 92.05000000,
            "levy": 20.25000000,
            "amount": 112.30000000,
            "total": 112.30000000,
            "reference": "xxxxxxxxx",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SOC.COOP. A R.L.",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SOC.COOP. A R.L.",
                        "code": "14",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Nursery",
                "street": "Via Example N. 1",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-26T12:02:17.1079168"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "3/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 2,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-26T11:59:25.1846421",
            "documentDate": "2025-06-26T00:00:00",
            "lastModifyDate": "2025-06-26T11:59:25.1846432",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": false,
            "rateableRows": 582.50000000,
            "rateable": 582.50000000,
            "levy": 23.30000000,
            "amount": 605.80000000,
            "total": 605.80000000,
            "reference": "xxxxxxxxx",
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company S.R.L",
                        "secondName": "",
                        "alias": "",
                        "name": "Company S.R.L",
                        "code": "6",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Company S.R.L.",
                "street": "Via Example N. 25/2",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-26T11:59:25.2856895"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "2/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        },
        {
            "type": {
                "groupType": "ORD",
                "originKind": "supplier",
                "refKind": "customer",
                "firstAccountingVisible": false,
                "firstAccountingCreateDocument": false,
                "firstAccountingEditDocument": false,
                "firstAccountingSign": 1,
                "batchSingle": false,
                "batchAutomaticOnly": false,
                "defaultBatchRequired": false,
                "showArticleOverride": false,
                "description": "Customer Order",
                "code": "2",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "incremental": 1,
            "year": 2025,
            "version": 0,
            "creationDate": "2025-06-25T12:16:00.2260585",
            "documentDate": "2025-06-25T00:00:00",
            "lastModifyDate": "2025-06-25T12:26:26.2391669",
            "isRevisioned": false,
            "isLocked": false,
            "isClosed": false,
            "isDeleted": false,
            "autoImported": false,
            "ignoreTopCompany": true,
            "rateableRows": 279.35000000,
            "rateable": 279.35000000,
            "levy": 61.46000000,
            "amount": 340.81000000,
            "total": 340.81000000,
            "stakeholders": [
                {
                    "stakeholder": {
                        "vatNumber": "xxxxxxxxx",
                        "fiscalCode": "",
                        "email": "email@example.com",
                        "legalEmail": "",
                        "invoiceLegalEmail": "",
                        "phone": "",
                        "mobilePhone": "",
                        "interchangeCode": "XXXXXXX",
                        "lastModifyDate": "0001-01-01T00:00:00",
                        "autoImported": false,
                        "firstName": "Company SRL",
                        "secondName": "",
                        "alias": "",
                        "name": "Company SRL",
                        "code": "192",
                        "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    },
                    "kind": "customer"
                }
            ],
            "address": {
                "description": "Relax Area",
                "street": "Via Example 20",
                "city": "City",
                "province": "PR",
                "zipCode": "00000",
                "country": "ITA",
                "fullCity": "City(PR)",
                "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "status": {
                "status": {
                    "color": "#1CBCD8",
                    "groupType": "bizdoc",
                    "locked": false,
                    "description": "In verification",
                    "code": "26",
                    "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                },
                "date": "2025-06-25T12:16:00.326987"
            },
            "nextStatus": [],
            "payments": [],
            "paymentHoldingTypes": [],
            "totalHoldingTypesAmount": 0,
            "movedInChildrenRows": false,
            "hasNotifies": false,
            "hasCalls": false,
            "childrenTypes": [],
            "description": "",
            "code": "1/2025",
            "identity": "anon-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        }
    ]);

    onTableEvent(event: any) {
        console.log('Table event:', event);
    }
}
